### ISSUE TITLE
api.js stops with error when search for non existing image

### ISSUE THREAD

**Issue by akudrya** [developmentseed/landsat-api#6]
I searched for an image which was newer then my version of image metadata.
error log:

``` javascript
{"name":"openfda-api-logger","hostname":"akudrya-2.local","pid":17920,"level":30,"msg":"Request complete","time":"2015-04-13T01:32:10.681Z","v":0}
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at ServerResponse.res.write (/Users/akudrya/GitHub/landsat-api/node_modules/express/node_modules/connect/node_modules/compression/index.js:112:17)
    at ServerResponse.res.end (/Users/akudrya/GitHub/landsat-api/node_modules/express/node_modules/connect/node_modules/compression/index.js:118:14)
    at ServerResponse.res.send (/Users/akudrya/GitHub/landsat-api/node_modules/express/lib/response.js:154:8)
    at ServerResponse.res.json (/Users/akudrya/GitHub/landsat-api/node_modules/express/lib/response.js:196:15)
    at /Users/akudrya/GitHub/landsat-api/api.js:183:16
    at tryCatch1 (/Users/akudrya/GitHub/landsat-api/node_modules/elasticsearch/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/Users/akudrya/GitHub/landsat-api/node_modules/elasticsearch/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/akudrya/GitHub/landsat-api/node_modules/elasticsearch/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/akudrya/GitHub/landsat-api/node_modules/elasticsearch/node_modules/bluebird/js/main/promise.js:868:14)
```

**Comment by scisco** [comment]
@akudrya  Could you share the query you ran. That'd help me to reproduce the error.

**Comment by akudrya** [comment]
http://localhost:8000/landsat?search=LC80440342015080LGN00
Latest record in my metadata.cvs 
LC81501172015071LGN00,OLI_TIRS,2015-03-12,2015-03-12,Y,http://earthexplorer.usgs.gov/browse/landsat_8/2015/150/117/LC81501172015071LGN00.jpg,150,117,-77.90494,11.77273,-79.17391,17.97203,-78.97702,4.90168,-80.38047,10.90453,-79.14105,11.38992,0,7.19,,,,,DAY,,5.70544807,78.45694454,LGN,2015:071:06:13:38.7626450,2015:071:06:14:10.5326410,,9,,,,,,,,,,,,,,,,,,,,,L1GT,http://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8&ordered=LC81501172015071LGN00,,,,,,,,,,,,,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NADIR

**Comment by scisco** [comment]
no longer relevant
